name: "Qwiet preZero Scan"
description: "Pipeline that will perform Qwiet Scanning"
emoji: ":rocket:"
tags: ["appsec"]
steps:
  - label: ":white_check_mark: Test"
    command: |
      curl https://cdn.shiftleft.io/download/sl > ./sl && chmod a+rx ./sl
      ./sl analyze --wait --app myApp  --tag branch="$BUILDKITE_BRANCH" .
      echo "====================================="
      echo ${github-pull-request-plugin-number}
      echo "====================================="
      echo ${BUILDKITE_PULL_REQUEST}
      echo "====================================="
      ./sl check-analysis --v2 --app myApp  --config shiftleft.yml --github-pr-number=${BUILDKITE_PULL_REQUEST} --github-pr-user=${BUILDKITE_BUILD_AUTHOR} --github-pr-repo=${BUILDKITE_REPO} --github-token=${GITHUB_TOKEN}
    key: Qwiet Scan
    env:
      - GITHUB_TOKEN=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
