name: "Qwiet preZero Scan"
description: "Pipeline that will perform Qwiet Scanning"
emoji: ":rocket:"
tags: ["appsec"]

env:
  GITHUB_TOKEN: "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"
steps:
  - label: ":white_check_mark: Test"
    command: |
      curl https://cdn.shiftleft.io/download/sl > ./sl && chmod a+rx ./sl
      #./sl analyze --wait --app myApp  --tag branch="$BUILDKITE_BRANCH" .
      url=$${BUILDKITE_REPO}
      basename=$$(basename $$url)
      reponame=$${basename%.*}

      temp=echo $${url} | sed -nr  's/^(https|git)(:\/\/|@)([^\/:]+)[\/:]([^\/:]+)\/(.+).git$$/\4\//p'
      echo "===================================="
      echo $${temp}
      echo "===================================="
      echo $${url}

      ./sl check-analysis --v2 --app myApp  --config shiftleft.yml --github-pr-number=$${BUILDKITE_PULL_REQUEST} --github-pr-user='elangosenthilnathan' --github-pr-repo=$${reponame} --github-token='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'
    key: QwietScan

