name: "Qwiet preZero Scan"
description: "Pipeline that will perform Qwiet Scanning"
emoji: ":rocket:"
tags: ["appsec"]

env:
  GITHUB_TOKEN: "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"
steps:
  - label: ":white_check_mark: Test"
    command: |
      curl https://cdn.shiftleft.io/download/sl > ./sl && chmod a+rx ./sl
      #./sl analyze --wait --app myApp  --tag branch="$BUILDKITE_BRANCH" .
      url=$${BUILDKITE_REPO}
      basename=$$(basename $$url)
      reponame=$${basename%.*}

      temp=echo $${url} | sed -nr  's/^(https|git)(:\/\/|@)([^\/:]+)[\/:]([^\/:]+)\/(.+).git$$/\4\/\5/p'
      echo "===================================="
      echo $${temp}
      echo "====================================="
      echo $${BUILDKITE_BUILD_AUTHOR}
      echo "======================================"
      echo $${BUILDKITE_BUILD_AUTHOR_EMAIL}
      echo "======================================"
      ./sl check-analysis --v2 --app myApp  --config shiftleft.yml --github-pr-number=$${BUILDKITE_PULL_REQUEST} --github-pr-user='elangosenthilnathan' --github-pr-repo=$${reponame} --github-token=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
    key: QwietScan

